openapi: '3.0.2'
info:
  title: Short.io API
  version: '1.3'
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  contact:
    name: David Gerard
servers:
  - url: https://api.short.io/api
    description: Short.io API
paths:
  /domains:
    get:
      summary: Get all domains
      description: Get all domains
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: apiKey
      in: header
security:
  - apiKey: []
